name: NoGit CI

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PowerShell Module
        shell: pwsh
        run: |
          Import-Module ./tools/ProjectBuilder/ProjectBuilder.psd1
          Build-Module -SourcePath ./module/NoGit -OutputDirectory ./Output

      - name: Upload Built Module
        uses: actions/upload-artifact@v4
        with:
          name: NoGitModule
          path: ./Output/*.nupkg

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ build ]
    runs-on: windows-latest
    steps:
      - name: Download Built Module
        uses: actions/download-artifact@v4
        with:
          name: NoGitModule
          path: ./Output

      - name: Publish to PowerShell Gallery
        shell: pwsh
        run: |
          $nupkg = Get-ChildItem -Path ./Output -Filter *.nupkg | Select-Object -First 1
          dotnet nuget push $nupkg.FullName `
            --api-key $env:PSGALLERY_TOKEN `
            --source 'https://www.powershellgallery.com/api/v2/package' `
            --no-symbols
        env:
          PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
