name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PowerShell Modules
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module -Name ModuleBuilder -Force -Scope CurrentUser
          Install-Module -Name Pester -Force -Scope CurrentUser

      - name: Run build.ps1
        shell: pwsh
        run: .\build.ps1 -Configuration Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: NoGit
          path: module/NoGit/Output

  publish:
    needs: build
    if: github.event_name == 'release'
    runs-on: windows-latest
    env:
      PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: NoGit
          path: .

      - name: Publish to PowerShell Gallery
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          $manifestPath = 'module/NoGit/NoGit.psd1'
          $manifest = Import-PowerShellDataFile $manifestPath
          $version = [string]$manifest.ModuleVersion
          Write-Host "Preparing to publish version $version..."

          $existing = Find-Module -Name 'NoGit' -Repository PSGallery -ErrorAction SilentlyContinue
          if ($existing -and $existing.Version -eq $version) {
              Write-Host "Version $version already exists on PSGallery. Skipping publish."
              exit 0
          }

          $modulePath = Join-Path (Get-Location) 'module/NoGit/Output'
          Publish-Module -Path $modulePath -NuGetApiKey $env:PSGALLERY_TOKEN -ErrorAction Stop
