name: NoGit CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build NoGit Module
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ModuleBuilder
        shell: pwsh
        run: Install-Module ModuleBuilder -Scope CurrentUser -Force

      - name: Build Module
        shell: pwsh
        run: |
          Build-Module -SourcePath ./module/NoGit -OutputDirectory ./Output

      - name: Upload Module Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PSModule
          path: ./Output/*.nupkg

  publish:
    name: Publish to PowerShell Gallery
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build
    runs-on: windows-latest
    steps:
      - name: Download Built Module
        uses: actions/download-artifact@v4
        with:
          name: PSModule
          path: ./Output

      - name: Publish to PowerShell Gallery
        shell: pwsh
        run: |
          dotnet nuget push './Output/*.nupkg' \
            --api-key $env:PSGALLERY_TOKEN \
            --source 'https://www.powershellgallery.com/api/v2/package' \
            --no-symbols
        env:
          PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
