name: NoGit Release Pipeline

on:
  push:
    branches:
      - main
  release:
    types:
      - published

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build and Package
    runs-on: windows-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Install PowerShell ModuleBuilder
      shell: pwsh
      run: Install-Module ModuleBuilder -Force -Scope CurrentUser

    - name: Build module
      shell: pwsh
      run: |
        New-ModuleManifest -Path output/NoGit.psd1 -RootModule 'NoGit.psm1' -ModuleVersion '1.0.0'
        Build-Module -Path . -OutputDirectory output

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NoGit
        path: output/*.nupkg

  publish:
    name: Publish to PowerShell Gallery
    if: github.event_name == 'release'
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: NoGit
        path: ./output

    - name: Publish to Gallery
      shell: pwsh
      run: |
        dotnet nuget push "./output/*.nupkg" `
          --api-key $env:PSGALLERY_TOKEN `
          --source "https://www.powershellgallery.com/api/v2/package" `
          --no-symbols
      env:
        PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
