name: NoGit CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build NoGit Module
    runs-on: windows-latest
    outputs:
      module_path: ${{ steps.find_manifest.outputs.module_path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Output directory exists
        shell: pwsh
        run: New-Item -Path ./Output -ItemType Directory -Force | Out-Null

      - name: Install ModuleBuilder
        shell: pwsh
        run: Install-Module ModuleBuilder -Scope CurrentUser -Force

      - name: Build Module
        shell: pwsh
        run: Build-Module -SourcePath ./module/NoGit -OutputDirectory ./Output

      - name: Find module manifest
        id: find_manifest
        shell: pwsh
        run: |
          $manifest = Get-ChildItem -Path ./Output -Recurse -Filter '*.psd1' | Select-Object -First 1
          "module_path=$($manifest.FullName)" >> $env:GITHUB_OUTPUT
  publish:
    name: Publish to PowerShell Gallery
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: PSModule
          path: ./Output

      - name: Publish to Gallery
        shell: pwsh
        run: |
          $moduleManifest = Get-ChildItem -Path ./Output -Recurse -Filter '*.psd1' | Select-Object -First 1
          $module = Test-ModuleManifest -Path $moduleManifest.FullName
          Set-Location (Split-Path -Path $moduleManifest.FullName -Parent)
          Publish-Module -Name $module.Name -NuGetApiKey $env:PSGALLERY_TOKEN -Verbose
        env:
          PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
        
