name: NoGit CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build NoGit Module
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ModuleBuilder
        shell: pwsh
        run: Install-Module ModuleBuilder -Scope CurrentUser -Force

      - name: Build Module
        shell: pwsh
        run: |
          New-Item -Path ./Output -ItemType Directory -Force | Out-Null
          Build-Module -SourcePath ./module/NoGit -OutputDirectory ./Output

      - name: Upload module package
        uses: actions/upload-artifact@v4
        with:
          name: PSModule
          path: ./Output/**/*

  publish:
    name: Publish to PowerShell Gallery
    if: github.event_name == 'release'
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: PSModule
          path: ./Output

      - name: Publish to Gallery
        shell: pwsh
        run: |
          $moduleManifest = Get-ChildItem -Path ./Output -Recurse -Filter '*.psd1' | Select-Object -First 1
          $module = Test-ModuleManifest -Path $moduleManifest.FullName
          Set-Location (Split-Path -Path $moduleManifest.FullName -Parent)
          Publish-Module -Name $module.Name -NuGetApiKey $env:PSGALLERY_TOKEN -Verbose
        env:
          PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
